= Development notes and plans

== Backing storage options to consider

* Plain old filesystem
  (probably won’t scale with the level of caching granularity
  we might want to aspire to)
* https://rocksdb.org/[RocksDB] / https://github.com/google/leveldb[LevelDB]
* https://github.com/spacejam/sled[sled]
** https://tikv.org/[TiKV] for distributed stores would be interesting,
   though probably excessive (there’s not as much chance of conflict
   in a largely content‐addressed database)
* https://symas.com/lmdb/[LMDB]
* https://sqlite.org/[SQLite]

Investigate which of these options would need
an accompanying large blob storage system (certainly SQLite)
and then don’t bother using those options
because that would be way too much work.

== Reference format

0x00/`uu:…`:: A universally unique random identifier.
0x01/`b3:…`:: A https://github.com/BLAKE3-team/BLAKE3[BLAKE3] hash.
…:: Extensible! Let’s hope we never need more than 255 hash functions.

Hash/UUID payload is 31 bytes so that the reference as a whole
is 256 bits.

TODO: Come up with a name for `uu:…` identifiers that doesn’t clash
with standard 128 bit UUIDs.

----
# Hash a constant
$ mew ref 1234
b3:…

# Import and hash a file
$ mew ref -f ./file
b3:…

# Hash a file without importing into the forest
$ mew ref -n -f ./file
b3:…

# Download and import a file
$ mew ref -f https://example.com/example-1.0.tar.gz
b3:…

# Generate a unique random identifier
$ mew ref -u
uu:…
----

== Sketch out the mewl language

Somewhere between a purely functional shell
and https://dhall-lang.org/[Dhall];
implementation tightly integrated with the build store interface.

Ensuring adherence to object‐capability principles is Very Important™.

=== Typed tree structure sketch

[source,mewl]
----
TreeSpec : Type
Dir : Map PathComponent TreeSpec → TreeSpec
Blob : TreeSpec
Executable : TreeSpec

Tree : TreeType → Type
get : (p : PathComponent) → ∀ts ⇒ Tree (Dir ts) → (e : p ∈ ts) ⇒ Tree (value e)
get? : PathComponent → ∀ts ⇒ Tree (Dir ts) → Option (∃t · Tree t)
execute : Tree Executable → …
execute? : ∀t ⇒ Tree t → Option …

— guaranteed to contain bin/hello, which you can execute (including
— from build rules), and share/doc/hello/README, a plain blob, but can
— also contain arbitrary other trees in addition
hello-tree : Tree (Dir {
  "bin" = Dir {"hello" = Executable},
  "share" = Dir {"doc" = Dir {"hello" = Dir {"README" = Blob}}},
})

— hello-tree ▻ get "bin" : Tree (Dir {"hello" = Executable})
— execute (hello-tree ▻ get "bin" ▻ get "hello") : …
----

Could probably use row types for this:

[source,mewl]
----
— essentially mapping from identifiers to the specified type
Row : Type → Type

⦃
  bin : Dir ⦃hello : Executable⦄,
  share : Dir ⦃doc : Dir ⦃hello : Dir ⦃README : Blob⦄⦄⦄,
⦄ : Row TreeSpec
----

Then we can get nicer `bin : …` syntax by punning on the fact
that rows would also be used to specify record types.

== Investigate Guix properly

and raid it for ideas.

== Meta

=== Move nixpkgs{,-mozilla} pins to fetchFromGitHub

Easier to include in `cargo publish` tarballs.

=== Set up a more formal documentation system

And then preferably have it publish to https://mew.build/[mew.build].

=== Set up CI

Investigate Azure Pipelines and GitHub Actions.

=== Set up bors

This will probably be really annoying in the early stages of hacking,
depending on the latency.

It would be good to integrate the bors setup
with https://github.com/spotify/git-test[git-test]
to test all the commits of a pull request
rather than just the HEAD.

=== Set up and require commit signing

See above, though tapping a YubiKey a few times
when pushing to the public repository isn’t too bad.

=== Move to self‐hosted infrastructure

GitHub https://github.com/drop-ice/dear-github-2.0[supports ICE],
and it would be nice to have the root of trust for binary builds
under our direct control.

This would require manually administering build and VCS machines,
prevent the use of the existing bors implementation,
and substantially increase the barrier to contribution,
so it should be done carefully:
ideally people would still be able to contribute
via GitHub issues and pull requests
and have them automatically mirrored to the self‐hosted infrastructure.

=== Prohibit force pushes

let’s not get ahead of ourselves here
